💚 Added workflow for fuzzer with exit code

diff --git a/.github/workflows/run_examples.yml b/.github/workflows/run_examples.yml
--- a/.github/workflows/run_examples.yml
+++ b/.github/workflows/run_examples.yml
@@ -56,3 +56,16 @@ jobs:
       - name: Test Fuzzer
         working-directory: examples/fuzzer
         run: cargo run --manifest-path ../../Cargo.toml fuzz run fuzz_1
+  test_fuzzer_with_exit_code:
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@v3
+      - uses: ./.github/actions/setup-rust/
+      - uses: ./.github/actions/setup-solana/
+      - uses: ./.github/actions/setup-honggfuzz/
+        id: rust-setup
+      - uses: Swatinem/rust-cache@v2
+        name: Cache Rust and it's packages
+      - name: Test Fuzzer
+        working-directory: examples/fuzzer
+        run: cargo run --manifest-path ../../Cargo.toml fuzz run -w fuzz_1 && echo "Fuzzer did not find anything" || echo "Fuzzer found an Error"
